import Head from 'next/head'
import { ThemeContext } from '../components/Theme'
import Layout from '../components/Layout'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Technologies from '../components/Technologies'
import SectionDivider from '../components/SharedComponents/SectionDivider'
import { useContext } from 'react'

export default function Home() {

  const [ darkMode, toggleMode ] = useContext(ThemeContext)

  return (
    <div className={`${darkMode ? "dark" : ""}`}>
      <Head>
        <title>Rommel Velasco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulk.png" />
      </Head>
      <Layout>
        <Hero />
      
        <Projects />
       
        <Technologies />
        
      </Layout>
    </div>
  )
}
