import Head from 'next/head'
import ThemeProvider from '../components/Theme'
import Layout from '../components/Layout'
import Hero from '../components/Hero'

export default function Home() {

  return (
    <ThemeProvider>
      <Head>
        <title>Rommel Velasco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulk.png" />
      </Head>
      <Layout>
        <Hero />
      </Layout>
    </ThemeProvider>
  )
}
